### ISSUE TITLE
Dream worker name error(?)

### ISSUE THREAD

**Issue by D4di69** [Haidra-Org/AI-Horde#238]
Normal process is OK.
WebUI is crazy, every time i change a setting (right) or no settings at all and click 'save configuration' i ALWAYS get an error probably related to the worker name(?)

`Traceback (most recent call last):
  File "C:\Users\x\Desktop\kobold horde\AI-Horde-Worker-main\conda\envs\windows\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\x\Desktop\kobold horde\AI-Horde-Worker-main\conda\envs\windows\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\x\Desktop\kobold horde\AI-Horde-Worker-main\conda\envs\windows\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\x\Desktop\kobold horde\AI-Horde-Worker-main\conda\envs\windows\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\x\Desktop\kobold horde\AI-Horde-Worker-main\conda\envs\windows\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\x\Desktop\kobold horde\AI-Horde-Worker-main\conda\envs\windows\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\x\Desktop\kobold horde\AI-Horde-Worker-main\webui.py", line 316, in save_config
    elif cfgkey == "dreamer_name" and config[cfgkey] == "An Awesome Dreamer":
KeyError: 'dreamer_name'
`

**Comment by tazlin** [comment]
This issue appears to be stale. If you have any further problems, please open a new issue.
